# Station GitHub Action
# Run AI agents from Station bundles in GitHub Actions
#
# Usage:
#   - uses: cloudshipai/station-action@v1
#     with:
#       agent: 'My Agent'
#       task: 'Analyze the codebase'
#     env:
#       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#
# See: https://github.com/cloudshipai/station/tree/main/deployments/github-actions

name: 'Station'
description: 'Run AI agents from Station bundles in GitHub Actions workflows'
author: 'CloudShip AI'
branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  # =============================================================================
  # Agent Execution (Required)
  # =============================================================================
  agent:
    description: 'Name of the agent to run (as defined in your bundle/environment)'
    required: true

  task:
    description: 'Task description for the agent to execute'
    required: true

  # =============================================================================
  # Bundle Source (pick one, or use local environment)
  # =============================================================================
  environment:
    description: |
      Local environment name to use (e.g., 'production', 'default').
      Looks for ./environments/<name>/ in your repo.
      If not specified, uses 'default' environment.
    required: false
    default: 'default'

  bundle-url:
    description: |
      URL to download a Station bundle (.tar.gz).
      Use this to run agents from pre-built bundles hosted anywhere.
    required: false

  bundle-id:
    description: |
      CloudShip bundle ID (UUID) to download from CloudShip registry.
      Requires cloudship-api-key to be set.
    required: false

  cloudship-api-key:
    description: |
      CloudShip API key for downloading bundles by ID.
      Only required when using bundle-id.
    required: false

  # =============================================================================
  # AI Provider Configuration
  # =============================================================================
  provider:
    description: |
      AI provider to use: 'openai', 'anthropic', 'gemini', or 'ollama'.
      Defaults to 'openai'. Each provider requires its own API key:
        - openai: OPENAI_API_KEY
        - anthropic: ANTHROPIC_API_KEY
        - gemini: GOOGLE_API_KEY or GEMINI_API_KEY
        - ollama: No key needed, set base-url to your Ollama instance
    required: false
    default: 'openai'

  model:
    description: |
      AI model to use. Examples:
        - openai: gpt-4o, gpt-4o-mini, o1-preview
        - anthropic: claude-3-5-sonnet-20241022, claude-3-5-haiku-20241022
        - gemini: gemini-2.0-flash-exp, gemini-1.5-pro
        - ollama: llama3.2, codellama, mistral
      If not specified, uses provider's default model.
    required: false

  base-url:
    description: |
      Custom API base URL for:
        - Azure OpenAI: https://YOUR-RESOURCE.openai.azure.com/
        - Ollama: http://localhost:11434
        - OpenAI-compatible APIs: Your endpoint URL
    required: false

  # =============================================================================
  # Execution Options
  # =============================================================================
  timeout:
    description: 'Agent execution timeout in seconds (default: 300)'
    required: false
    default: '300'

  max-steps:
    description: 'Maximum number of agent steps (default: 50)'
    required: false
    default: '50'

  comment-pr:
    description: |
      Post agent results as a PR comment (true/false).
      Only works on pull_request events.
    required: false
    default: 'false'

  fail-on-error:
    description: 'Fail the workflow if agent execution fails (default: true)'
    required: false
    default: 'true'

  # =============================================================================
  # Station Configuration
  # =============================================================================
  version:
    description: 'Station CLI version to install (e.g., v0.22.0, latest)'
    required: false
    default: 'latest'

  debug:
    description: 'Enable debug logging (true/false)'
    required: false
    default: 'false'

outputs:
  result:
    description: 'Agent execution result (JSON)'
    value: ${{ steps.run.outputs.result }}

  exit-code:
    description: 'Agent exit code (0 = success)'
    value: ${{ steps.run.outputs.exit_code }}

  run-id:
    description: 'Station run ID for this execution'
    value: ${{ steps.run.outputs.run_id }}

runs:
  using: 'composite'
  steps:
    # =========================================================================
    # Step 1: Install Station CLI
    # =========================================================================
    - name: Install Station CLI
      id: install
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"

        if [ "$VERSION" = "latest" ]; then
          echo "📦 Fetching latest Station version..."
          VERSION=$(curl -sS https://api.github.com/repos/cloudshipai/station/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
        fi

        echo "📦 Installing Station CLI ${VERSION}..."

        # Detect OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        case "$ARCH" in
          x86_64) ARCH="amd64" ;;
          aarch64|arm64) ARCH="arm64" ;;
          armv7l) ARCH="arm" ;;
        esac

        # Download and install
        VERSION_NO_V="${VERSION#v}"
        DOWNLOAD_URL="https://github.com/cloudshipai/station/releases/download/${VERSION}/station_${VERSION_NO_V}_${OS}_${ARCH}.tar.gz"

        echo "Downloading from: $DOWNLOAD_URL"
        curl -fsSL "$DOWNLOAD_URL" -o /tmp/station.tar.gz
        tar -xzf /tmp/station.tar.gz -C /tmp
        chmod +x /tmp/stn
        sudo mv /tmp/stn /usr/local/bin/stn
        rm /tmp/station.tar.gz

        echo "✅ Station CLI ${VERSION} installed"
        stn --version

        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    # =========================================================================
    # Step 2: Prepare Bundle/Environment
    # =========================================================================
    - name: Prepare environment
      id: prepare
      shell: bash
      env:
        BUNDLE_URL: ${{ inputs.bundle-url }}
        BUNDLE_ID: ${{ inputs.bundle-id }}
        CLOUDSHIP_API_KEY: ${{ inputs.cloudship-api-key }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        WORKSPACE_DIR="${{ github.workspace }}"

        # Determine source type and prepare accordingly
        if [ -n "$BUNDLE_URL" ]; then
          echo "📦 Downloading bundle from URL..."
          mkdir -p /tmp/station-bundle
          curl -fsSL "$BUNDLE_URL" -o /tmp/station-bundle/bundle.tar.gz
          cd /tmp/station-bundle
          tar -xzf bundle.tar.gz
          rm bundle.tar.gz
          BUNDLE_PATH="/tmp/station-bundle"
          echo "bundle_path=$BUNDLE_PATH" >> $GITHUB_OUTPUT
          echo "source_type=bundle" >> $GITHUB_OUTPUT

        elif [ -n "$BUNDLE_ID" ]; then
          if [ -z "$CLOUDSHIP_API_KEY" ]; then
            echo "❌ Error: cloudship-api-key required when using bundle-id"
            exit 1
          fi

          echo "📦 Downloading bundle from CloudShip: $BUNDLE_ID"
          CLOUDSHIP_API_URL="${CLOUDSHIP_API_URL:-https://api.cloudshipai.com}"
          DOWNLOAD_URL="${CLOUDSHIP_API_URL}/api/public/bundles/${BUNDLE_ID}/download/"

          mkdir -p /tmp/station-bundle
          HTTP_CODE=$(curl -sS -w "%{http_code}" \
            -H "X-Registration-Key: ${CLOUDSHIP_API_KEY}" \
            -o /tmp/station-bundle/bundle.tar.gz \
            "$DOWNLOAD_URL")

          if [ "$HTTP_CODE" != "200" ]; then
            echo "❌ Error: Failed to download bundle (HTTP $HTTP_CODE)"
            exit 1
          fi

          cd /tmp/station-bundle
          tar -xzf bundle.tar.gz
          rm bundle.tar.gz
          BUNDLE_PATH="/tmp/station-bundle"
          echo "bundle_path=$BUNDLE_PATH" >> $GITHUB_OUTPUT
          echo "source_type=bundle" >> $GITHUB_OUTPUT

        else
          # Use local environment
          ENV_PATH="$WORKSPACE_DIR/environments/$ENVIRONMENT"
          if [ -d "$ENV_PATH" ]; then
            echo "📂 Using local environment: $ENVIRONMENT"
            echo "env_path=$ENV_PATH" >> $GITHUB_OUTPUT
            echo "source_type=environment" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Environment directory not found: $ENV_PATH"
            echo "   Creating minimal config..."
            echo "source_type=minimal" >> $GITHUB_OUTPUT
          fi
        fi

    # =========================================================================
    # Step 3: Initialize Station
    # =========================================================================
    - name: Initialize Station
      shell: bash
      env:
        STN_AI_PROVIDER: ${{ inputs.provider }}
        STN_AI_MODEL: ${{ inputs.model }}
        STN_AI_BASE_URL: ${{ inputs.base-url }}
        STN_DEBUG: ${{ inputs.debug }}
      run: |
        cd "${{ github.workspace }}"

        stn init --config /tmp/station-config.yaml --yes 2>/dev/null || true

        echo "✅ Station initialized"

    # =========================================================================
    # Step 3.5: Sync Environment (load agents and MCP configs)
    # =========================================================================
    - name: Sync environment
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        SOURCE_TYPE: ${{ steps.prepare.outputs.source_type }}
        BUNDLE_PATH: ${{ steps.prepare.outputs.bundle_path }}
        STN_DEBUG: ${{ inputs.debug }}
      run: |
        cd "${{ github.workspace }}"

        # Skip sync if minimal source (no environment directory)
        if [ "$SOURCE_TYPE" = "minimal" ]; then
          echo "⏭️ Skipping sync (minimal configuration)"
          exit 0
        fi

        # For bundles, sync from bundle directory
        if [ "$SOURCE_TYPE" = "bundle" ] && [ -n "$BUNDLE_PATH" ]; then
          cd "$BUNDLE_PATH"
        fi

        echo "🔄 Syncing environment: $ENVIRONMENT"
        echo "   Loading agents and MCP server configurations..."

        if stn sync "$ENVIRONMENT" --config /tmp/station-config.yaml -i=false 2>&1; then
          echo "✅ Environment synced successfully"

          # List available agents for debugging
          echo ""
          echo "📋 Available agents:"
          stn agent list --config /tmp/station-config.yaml --env "$ENVIRONMENT" 2>/dev/null || echo "   (no agents found)"
        else
          echo "⚠️ Warning: Sync failed, agent may not be available"
          echo "   Check that environments/$ENVIRONMENT/ exists and contains valid configs"
        fi

    # =========================================================================
    # Step 4: Run Agent
    # =========================================================================
    - name: Run agent
      id: run
      shell: bash
      env:
        # AI Provider Configuration (from inputs)
        STN_AI_PROVIDER: ${{ inputs.provider }}
        STN_AI_MODEL: ${{ inputs.model }}
        STN_AI_BASE_URL: ${{ inputs.base-url }}
        STN_DEBUG: ${{ inputs.debug }}
        # Execution config
        AGENT_NAME: ${{ inputs.agent }}
        AGENT_TASK: ${{ inputs.task }}
        ENVIRONMENT: ${{ inputs.environment }}
        MAX_STEPS: ${{ inputs.max-steps }}
        TIMEOUT: ${{ inputs.timeout }}
        SOURCE_TYPE: ${{ steps.prepare.outputs.source_type }}
        BUNDLE_PATH: ${{ steps.prepare.outputs.bundle_path }}
      run: |
        set +e  # Don't exit on error, capture exit code

        cd "${{ github.workspace }}"

        echo "🤖 Running agent: $AGENT_NAME"
        echo "📝 Task: $AGENT_TASK"
        echo "🔧 Provider: ${STN_AI_PROVIDER:-openai}"
        [ -n "$STN_AI_MODEL" ] && echo "🧠 Model: $STN_AI_MODEL"

        if [ "$SOURCE_TYPE" = "bundle" ] && [ -n "$BUNDLE_PATH" ]; then
          cd "$BUNDLE_PATH"
        fi

        RESULT=$(stn agent run "$AGENT_NAME" "$AGENT_TASK" \
          --config /tmp/station-config.yaml \
          --env "$ENVIRONMENT" \
          --tail 2>&1) || true

        EXIT_CODE=$?

        # Extract run ID from output if available
        RUN_ID=$(echo "$RESULT" | grep -o 'run_id.*' | head -1 | cut -d'"' -f3 || echo "")

        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

        # Store result (escape for GitHub Actions)
        EOF_MARKER="EOF_$(date +%s)"
        echo "result<<$EOF_MARKER" >> $GITHUB_OUTPUT
        echo "$RESULT" >> $GITHUB_OUTPUT
        echo "$EOF_MARKER" >> $GITHUB_OUTPUT

        if [ $EXIT_CODE -eq 0 ]; then
          echo "✅ Agent completed successfully"
        else
          echo "⚠️ Agent completed with exit code: $EXIT_CODE"
        fi

        # Return exit code for fail-on-error handling
        exit $EXIT_CODE

    # =========================================================================
    # Step 5: Post PR Comment (Optional)
    # =========================================================================
    - name: Post PR comment
      if: github.event_name == 'pull_request' && inputs.comment-pr == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const agentName = '${{ inputs.agent }}';
          const exitCode = '${{ steps.run.outputs.exit_code }}';
          const runId = '${{ steps.run.outputs.run_id }}';

          const statusEmoji = exitCode === '0' ? '✅' : '⚠️';
          const statusText = exitCode === '0' ? 'Completed' : 'Completed with warnings';

          const body = `## 🤖 Station Agent: ${agentName}

          ${statusEmoji} **Status**: ${statusText}

          **Task**: ${{ inputs.task }}

          **Workflow run**: https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}

          ---
          _Powered by [Station](https://github.com/cloudshipai/station)_`;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });

    # =========================================================================
    # Step 6: Handle Failure
    # =========================================================================
    - name: Check for failure
      if: steps.run.outputs.exit_code != '0' && inputs.fail-on-error == 'true'
      shell: bash
      run: |
        echo "❌ Agent execution failed with exit code: ${{ steps.run.outputs.exit_code }}"
        exit 1
