name: Infrastructure Analysis

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
      - 'docker/**'
  pull_request:
    paths:
      - 'terraform/**'
      - 'kubernetes/**'
      - 'docker/**'

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: cloudshipai/station-action@v1
        with:
          agent: 'Infrastructure Analyst'
          task: 'Analyze infrastructure code for security issues, cost optimization, and best practices'
          comment-pr: ${{ github.event_name == 'pull_request' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
