name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: cloudshipai/station-action@v1
        with:
          agent: 'Code Reviewer'
          task: 'Review this PR for bugs, security issues, and best practices. Focus on the changed files.'
          comment-pr: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
